
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package lexparse;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int OPTION_ZU = 8;
  public static final int ENDE = 3;
  public static final int KLAMMER_AUF = 4;
  public static final int ZUWEISUNG = 2;
  public static final int NICHTTERMINAL = 12;
  public static final int WDH_AUF = 9;
  public static final int EOF = 0;
  public static final int KLAMMER_ZU = 5;
  public static final int ODER = 6;
  public static final int OPTION_AUF = 7;
  public static final int TERMINAL = 11;
  public static final int WDH_ZU = 10;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ZUWEISUNG",
  "ENDE",
  "KLAMMER_AUF",
  "KLAMMER_ZU",
  "ODER",
  "OPTION_AUF",
  "OPTION_ZU",
  "WDH_AUF",
  "WDH_ZU",
  "TERMINAL",
  "NICHTTERMINAL"
  };
}

